# Copyritht © 2022 Marcin Różewski MDSANIMA

[tool.black]
line-length = 79
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[tool.isort]
profile = 'black'
src_paths = ['src', 'tests']
force_single_line = true
lines_before_imports = 2
lines_after_imports = 2
treat_all_comments_as_code = true
extend_skip = ['.md', '.json']
